

data "aws_iam_policy_document" "okta_master_policy" {
    statement {
        sid = "1"
        actions = [
            "iam:GetPolicy",
            "iam:GetPolicyVersion",
            "iam:GetRole",
            "iam:GetRolePolicy",
            "iam:ListAttachedRolePolicies",
            "iam:ListRolePolicies",
            "iam:ListAccountAliases",
            "iam:ListRoles",
        ]
        resources = ["*"]
    }
}

variable "saml_metadata_doc" {
   description = "Local file path to a saml descriptor, this is generated by your okta admin"
}
resource "aws_iam_saml_provider" "okta" {
  name                   = "okta"
  saml_metadata_document = "${file(var.saml_metadata_doc)}"
}

resource "aws_iam_policy" "okta_master_account_policy" {
    name = "okta_master_account_policy"
    policy = "${data.aws_iam_policy_document.okta_master_policy.json}"
}


module "users" {
    source = "git::ssh://git@stash.corp.code42.com:7999/dt/terraform-iam-role-modules.git//modules/user"
    # source = "../../../../terraform-iam-role-modules/modules/user"

    user = "OktaSSOUser"
    policy_arns = ["${aws_iam_policy.okta_master_account_policy.arn}"]
}


output "okta_access_key" {
  value = "${module.users.aws_access_id}"
}
output "okta_secret_key" {
  value = "${module.users.aws_secret_key}"
}


output "provider_arn"  {
    value = "${aws_iam_saml_provider.okta.arn}"
}

