---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: gradle
    tag: 'jdk8-alpine'

inputs:
  - name: source
  - name: version
outputs:
  - name: dist
caches:
  - path: source/.gradle

run:
  dir: source
  path: ci/tasks/build
